### ISSUE TITLE
No transcriptions for s0103a audio file 

### ISSUE THREAD

**Issue by Saurabhbhati** [bootphon/tde#4]
Hey,

Both english.phn and english.wrd files are missing transcriptions for s0103a audio file. english.split contains silence/speech split for s0103a audio file. 

Please check the .phn and .wrd files for english.

Thank You

**Comment by jubenjum** [comment]
Hi,

Are you working on the 2015 or 2017 challenge? The master branch is for the 2015 challenge and yes there is that data missing, however if the transcriptions are missing then there won't be any evaluation for that file (s0103a). I'll check for the missing data.

Thanks for that information.

Juan

**Comment by Saurabhbhati** [comment]
Hey,

I am currently working on 2015 challenge. 

Saurabh

**Comment by jubenjum** [comment]
I checked the logs and it seems that that speech file was removed from the 2015 challenge evaluation. I removed that data from the split file to keep a clean database.

Thanks to point out that problem

Juan

**Comment by Saurabhbhati** [comment]
Thank you!
